# Dependencies
gems: [jekyll-gist]
markdown:         kramdown
highlighter:      rouge
plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            My Blog
description:      "Geon Park's blog"
baseurl:          /

author:
  name:           'Geon Park'
  url:            https://twitter.com/geonpark_ai

paginate:         5
